name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  client-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install Client Dependencies
        run: npm install --prefix client

      - name: Client Security Scan
        run: npm audit --prefix client

      - name: Run Client Lint
        run: npm run lint --prefix client

  server-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Install Server Dependencies
        run: npm install --prefix server

      - name: Server Security Scan
        run: npm audit --prefix server

      - name: Build Server
        run: npm run build --prefix server

      - name: Start Server & Wait
        run: |
          BITRIX_WEBHOOK=http://dummy npm start --prefix server &
          npx wait-on http-get://localhost:3000/health -t 60000
